{{- if .Values.client.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.client.name }}-sa
  labels:
    app: {{ .Values.client.name }}
    component: client-simulator
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.client.name }}-pod-reader
  labels:
    app: {{ .Values.client.name }}
    component: client-simulator
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.client.name }}-pod-reader-binding
  labels:
    app: {{ .Values.client.name }}
    component: client-simulator
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.client.name }}-pod-reader
subjects:
- kind: ServiceAccount
  name: {{ .Values.client.name }}-sa
{{- end }}
