{{- if and .Values.prometheus.enabled .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: a2a-demo-services
  labels:
    app: a2a-demo
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  selector:
    matchLabels:
      chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  endpoints:
  - port: http
    path: /metrics
    interval: {{ .Values.prometheus.serviceMonitor.interval }}
{{- end }}
